# Generated by Django 4.0.6 on 2022-07-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_detail',
            name='password',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
