# Generated by Django 4.0.6 on 2022-07-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0002_driver_detail_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver_detail',
            name='driving_licence_photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='driver_detail',
            name='registration_card_photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
