# Generated by Django 4.0.6 on 2022-07-22 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0003_alter_driver_detail_driving_licence_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver_detail',
            name='driving_licence_photo',
        ),
        migrations.RemoveField(
            model_name='driver_detail',
            name='registration_card_photo',
        ),
    ]
