# Generated by Django 4.0.6 on 2022-07-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0005_alter_driver_detail_driving_licence_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver_detail',
            name='driving_licence_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='driver_detail',
            name='vehicle_registration_number',
            field=models.CharField(max_length=100),
        ),
    ]
