# Generated by Django 3.1.7 on 2022-07-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0006_alter_driver_detail_driving_licence_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver_detail',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
