# Generated by Django 3.1.7 on 2022-07-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0007_auto_20220727_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver_detail',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='driver_detail',
            name='phone_number',
            field=models.IntegerField(unique=True),
        ),
    ]
