# Generated by Django 3.1.7 on 2022-07-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0008_auto_20220727_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_detail',
            name='driving_licence_photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='driver_detail',
            name='registration_card_photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='driver_detail',
            name='driving_licence_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='driver_detail',
            name='vehicle_registration_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
