# Generated by Django 4.0.6 on 2022-07-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0015_alter_driver_detail_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver_detail',
            name='phone_number',
            field=models.CharField(max_length=12),
        ),
    ]
