# Generated by Django 4.0.6 on 2022-07-28 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0022_alter_driver_detail_driving_licence_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver_detail',
            name='phone_number',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 12 digits allowed.", regex='^\\+?1?\\d{10,12}$')]),
        ),
    ]
